spring:
  application:
    name: api-gateway
server:
  port: 14000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: oauth-server
    ui:
      path: /ui/**
      serviceId: ui
  sensitiveHeaders:
  add-proxy-headers: true

security:
  oauth2:
    client:
      clientId: api-gateway
      clientSecret: 123456
      accessTokenUri: http://localhost:14000/auth/oauth/token
      userAuthorizationUri: http://localhost:14000/auth/oauth/authorize
      #logOutUri: http://localhost:11000/auth/oauth/exit
    resource:
      userInfoUri: http://localhost:14000/auth/me
      preferTokenInfo: false
#      token-info-uri: http://localhost:11000/oauth/check_token
#      prefer-token-info: true
#      jwt:
#        key-uri: http://localhost:11000/oauth/token_key