server:
  port: 11001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

security:
  oauth2:
    resource:
      id: ui
      userInfoUri: http://localhost:14000/auth/me
      preferTokenInfo: false
      #token-info-uri: http://localhost:14000/auth/oauth/check_token
      #prefer-token-info: true
      #jwt:
        #key-uri: http://localhost:14000/auth/oauth/token_key

debug: false

spring:
  application:
    name: ui