spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:mysql://192.168.1.250:3366/platform?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0       # Redis数据库索引（默认为0）
    host: 192.168.1.250
    port: 6379
    password: 7bb75e33-6dcd-4802-ac4e-047212d0efe5      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 11000


